// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

declare global {
    interface Window {
        __TAURI_INVOKE__<T>(cmd: string, args?: Record<string, unknown>): Promise<T>;
    }
}

const invoke = window.__TAURI_INVOKE__;

export function errorPopup(msg: string) {
    return invoke<null>("error_popup", { msg })
}

export function loadBackupList(refresh: boolean) {
    return invoke<DirMap<null>>("load_backup_list", { refresh })
}

export function getBackup(oldB: string, newB: string, refresh: boolean) {
    return invoke<DirMap<LoadedBackupItem>>("get_backup", { oldB,newB,refresh })
}

export function backupsInfo() {
    return invoke<BackupInfo[]>("backups_info")
}

export type BackupInfo = { old: string; new: string; loading: boolean }
export type LoadedBackupItem = { size: number }
export type DirMap<I> = { map: { [key: string]: { [key: I]: null } } }
